userEarned,
estimatedDai,
estimatedUsdc,
estimatedUsdt,
estimatedTotal,
setEstimatedDai,
setEstimatedUsdc,
setEstimatedUsdt,
setEstimatedTotal,
setUserDeposit,
setUserEarned,
setCrvValueUSD,
setCrvValue,
setTotalLP,
setUserLP,
setUsdtPoolBal,
setUsdcPoolBal,
setDaiPoolBal,
setUsdtAllowance,
setUsdcAllowance,
setDaiAllowance,
setWalletUSDCBalance,
setDepositDAIValue,
setDepositUSDCValue,
setDepositUSDTValue,
setWalletDAIBalance,
setWalletUSDTBalance,
}}
>
{children}
</AuthContext.Provider>
  );
};