import Head from "next/head";
import Earnings from "@/components/Cards/Earning";
import { useContract } from "wagmi";
import SaaveABI from "@/abis/abi.json";
import Saave from "@/components/Cards/Saave";

export default function Home() {
  const contract = useContract({
    address: "0xBFbA56f89f343dc43B99Dcb0c6e30045d2D2E948",
    abi: SaaveABI,
  });

  return (
    <>
      <Head>
        <title>SAAVE | Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-Inter">
        <Earnings />
        <Saave />
      </main>
    </>
  );
}
