import Head from "next/head";
import Panel from "@/components/Panel";
import Earnings from "@/components/Earning";

export default function Home() {
  return (
    <>
      <Head>
        <title>SAAVE | Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Earnings />
        <Panel />
      </main>
    </>
  );
}
